# Login
# @name token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "JohnDoe@tux.com",
  "password": "password"
}

###

@authToken = {{token.response.body.token}}
# Get all nodes at depth 4 and above
GET http://localhost:3000/nodes?depth=4
Authorization: Bearer {{authToken}}

###

# Get only nodes at depth 4
GET http://localhost:3000/nodes?depth=1&parentId=29
Authorization: Bearer {{authToken}}

###

# add a root node
POST http://localhost:3000/nodes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Root Node",
  "type": "folder",
  "parentId": null
}

###

# get Root node
# @name root
GET http://localhost:3000/nodes/root
Authorization: Bearer {{authToken}}

###

@rootId = {{root.response.body.node.id}}

# add a node
# @name parentId
POST http://localhost:3000/nodes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Node 1",
  "type": "file",
  "parentId": {{rootId}}
}

###

@parent = {{parentId.response.body.node.id}}

# add a grandchild node
POST http://localhost:3000/nodes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Node 2",
  "type": "folder",
  "parentId": {{parent}}
}

### Add node to static parentId
POST http://localhost:3000/nodes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Node 3",
  "type": "folder",
  "parentId": 29
}

###

PUT http://localhost:3000/nodes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": {{parent}},
  "name": "Node 1",
  "type": "folder",
  "parentId": {{rootId}}
}


###

DELETE http://localhost:3000/nodes
Authorization: Bearer <token>

Content-Type: application/json

{
  "id": 1
}
