POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "JohnDoe@tux.com",
  "password": "123456",
  "role": "admin"
}

###

# @name token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "JohnDoe@tux.com",
  "password": "123456"
}

###

@authToken = {{token.response.body.token}}
GET http://localhost:3000/auth/users
Authorization: Bearer {{authToken}}
